### ISSUE TITLE
Where is plpfuse?

### ISSUE THREAD

**Issue by mikeydelamonde** [rrthomas/plptools#10] opened 2024-02-23 13:19 UTC
I have run `make install` on my mac and got ncpd with plpftp working. I can see the following commands in these locations

/usr/local/bin/plpftp
/usr/local/bin/sisinstall
/usr/local/sbin/ncpd
/usr/local/sbin/plpprintd

However, I can't find where plpfuse is, and there's no mention of it in the output of make. I have MacFUSE installed so hoping that I can use plpfuse. Any ideas? Thanks for your help!

**Comment by mikeydelamonde** [comment] 2024-02-23 14:04
Ah OK. I'll try that again as I might have installed MacFuse after configure

**Comment by mikeydelamonde** [comment] 2024-02-23 14:13
Fuse related output is:
checking for fuse >= 2.6... yes
config.status: creating plpfuse/Makefile
config.status: creating doc/plpfuse.man

**Comment by rrthomas** [comment] 2024-02-23 14:15
Great, looks like you're good to go!

**Comment by mikeydelamonde** [comment] 2024-02-23 14:30
Hmm then ran `./configure` then `make` then `make install` but no mention of plpfuse in the outputs. Any other ideas?

**Comment by mikeydelamonde** [comment] 2024-02-23 14:40
Could it be that there are some errors when running make install
```
Making install in plpftp
g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I..  -I../lib -I../intl   -g -O2 -MT ftp.o -MD -MP -MF .deps/ftp.Tpo -c -o ftp.o ftp.cc
ftp.cc:1518:36: error: assigning to 'Function *' (aka 'int (*)(const char *, int)') from incompatible type 'char *(const char *, int)': different return type ('int' vs 'char *')
    rl_completion_entry_function = null_completion;
                                   ^~~~~~~~~~~~~~~
ftp.cc:1532:2: error: use of undeclared identifier 'rl_filename_quoting_desired'; did you mean 'rl_filename_completion_desired'?
        rl_filename_quoting_desired = 1;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
        rl_filename_completion_desired
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/readline/readline.h:131:13: note: 'rl_filename_completion_desired' declared here
extern int              rl_filename_completion_desired;
                        ^
ftp.cc:1566:24: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    rl_readline_name = "plpftp";
                       ^
ftp.cc:1567:36: error: assigning to 'Function *' (aka 'int (*)(const char *, int)') from incompatible type 'char *(const char *, int)': different return type ('int' vs 'char *')
    rl_completion_entry_function = null_completion;
                                   ^~~~~~~~~~~~~~~
ftp.cc:1569:38: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    rl_basic_word_break_characters = " \t\n\"\\'`@><=;|&{(";

```

It doesn't seem to affect plpftp, but perhaps stops the execution?

**Comment by rrthomas** [comment] 2024-02-23 14:44
Yes, you got a compilation error above. You are not using readline. See the macOS-specific instructions in `README`.

You can check the exit status to see if you got an error if you're not sure from the sometimes-confusing output of make.

**Comment by rrthomas** [comment] 2024-02-23 14:45
@kapfab, I had not fully understood that macOS is claiming to have readline in some way (via libedit?) but it's not real. I could really do with an autoconf check for this, to avoid confusing macOS users like this. Any ideas?

**Comment by rrthomas** [comment] 2024-02-23 14:50
Thanks, I'll look into that.

**Comment by kapfab** [comment] 2024-02-23 14:51
Or maybe play with libhistory support (macOS has none AFAIR).

**Comment by mikeydelamonde** [comment] 2024-02-23 14:52
I did install readline, just fyi. Homebrew says `Warning: readline 8.2.7 is already installed and up-to-date.`

**Comment by rrthomas** [comment] 2024-02-23 14:52
OK, looks like libedit claims readline v4. Version 5 is already ancient, so I guess I can check for that.

**Comment by mikeydelamonde** [comment] 2024-02-23 14:54
Yes the output of make is: 
`make[1]: *** [ftp.o] Error 1
make: *** [install-recursive] Error 1`

**Comment by rrthomas** [comment] 2024-02-23 14:55
@mikeydelamonde see the instructions in `README`: you have to point the compiler at the right readline!

**Comment by mikeydelamonde** [comment] 2024-02-23 14:58
Ah! Sorry!

**Comment by rrthomas** [comment] 2024-02-23 15:27
OK, I see the problem, which is that Apple uses an outdated libedit that is simply broken. I think I can avoid both a macOS-specific test while keeping libedit compatibility by testing for readline version ≥ 4.3, as the fixed BSD libedit advertises 4.3, while Apple's libedit advertises 4.2.

**Comment by rrthomas** [comment] 2024-02-23 22:56
I have added a version check for libreadline to git master; I would be most obliged if someone could check that it now gives a nice error on macOS when GNU readline (or sufficiently new libedit) is not installed.

**Comment by rrthomas** [comment] 2024-02-24 10:37
> It doesn't seem to affect plpftp, but perhaps stops the execution?

I just realised I hadn't noticed this: plpftp was built despite the error. Weird. You had some bone fide errors, including an assignment to an unknown identifier. So there is no way that compilation produced an object file. I wonder how you got a plpftp binary…

**Comment by rrthomas** [comment] 2024-02-24 11:01
Closing this issue; I will shortly make a new release with the build system fixes.

**Comment by kapfab** [comment] 2024-02-24 11:01
Wasn't it just the binary generated by the previous successful build?

**Closed by rrthomas** 2024-02-24 11:01 UTC

**Comment by rrthomas** [comment] 2024-02-24 11:04
I had the impression from the report that @mikeydelamonde didn't change anything readline-related up to the point where he reported the error.

**Comment by mikeydelamonde** [comment] 2024-02-24 11:23
I think that the previous build I did run the command that refers to the
installed readline. I did that again now and didn’t get the errors,
although still no plpfuse.

**Comment by rrthomas** [comment] 2024-02-24 11:38
@mikeydelamonde Thanks for the explanation. If `configure` says it is detecting FUSE OK, but is not building plpfuse, then that sounds like a bug and the issue should be reopened. To see what's happening, in the top-level directory, please `grep BUILD_PLPFUSE config.log` and also `grep SUBDIRS Makefile` and show the results.

**Comment by mikeydelamonde** [comment] 2024-02-24 12:39
I just did a fresh git pull and ran everything again, here's the results:

```
grep BUILD_PLPFUSE config.log
BUILD_PLPFUSE_FALSE=''
BUILD_PLPFUSE_TRUE='#'
```
```grep SUBDIRS Makefile
DIST_SUBDIRS = po lib ncpd plpftp plpprint sisinstall doc plpfuse
SUBDIRS = po lib ncpd plpftp plpprint sisinstall doc $(am__append_1)
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \```

**Comment by rrthomas** [comment] 2024-02-24 14:11
Looks good, what happens when you build?

--
https://rrt.sc3d.org

**Comment by kapfab** [comment] 2024-02-24 14:58
Same here: no error but `plpfuse` is not build.

Looking at the `configure` output, I see:
```
checking for fuse >= 2.6... yes
checking for attr/attributes.h... no
```
`attr/attributes.h` seems to be required by `plpfuse`, that might be why it does not get built.

**Comment by rrthomas** [comment] 2024-02-24 15:05
But it will have tried to build it. What do the logs say?

--
https://rrt.sc3d.org

**Comment by kapfab** [comment] 2024-02-24 15:20
No, it doesn’t even try.

`Makefile` shows:
```
SUBDIRS = po lib ncpd plpftp plpprint sisinstall doc $(am__append_1)
```
but `am__append_1` is commented:
```
#am__append_1 = plpfuse
```

**Comment by kapfab** [comment] 2024-02-24 15:23
Seeing
```
checking for fuse >= 2.6... yes
config.status: creating plpfuse/Makefile
config.status: creating doc/plpfuse.man
```
and
```
DIST_SUBDIRS = po lib ncpd plpftp plpprint sisinstall doc plpfuse
```
initially made me think everything was fine.

**Comment by kapfab** [comment] 2024-02-24 16:12
I didn’t expect that, but `plpfuse` builds without any related warning when running `make` in its module directory after commenting the `attr/attributes.h` include and the `-lattr` option.

I have no way to check how the binary behaves with MacFuse running as I don’t want to circumvent the OS security settings to actually activate MacFuse on my machine but I’d expected to get compiling errors due to libattr missing…

**Comment by rrthomas** [comment] 2024-02-24 16:21
Sorry, I misread your results earlier. Indeed, it's not trying to build plpfuse for you, and the reason is that it needs libattr.

**Comment by kapfab** [comment] 2024-02-24 16:27
But does `plpfuse` actually need `libattr` ? I can’t find it used anywhere in the source code.

**Comment by rrthomas** [comment] 2024-02-24 16:32
Good question, it seems that it's only preprocessor constants that are needed. However, in principle there's nothing that says they will be preprocessor constants rather than values defined in the library, and in any case, the relevant headers are needed.

**Comment by rrthomas** [comment] 2024-02-24 16:44
I've committed a change so that only the headers are now required; can you possibly build master HEAD @kapfab and let me know if that fixes things?

**Comment by kapfab** [comment] 2024-02-24 16:56
I can't try for now but the header file won't be found anyway.
Do you know which `libattr` attributes are used? They might be found in another macOS standard header…

**Comment by rrthomas** [comment] 2024-02-24 16:57
As I understand it, macOS has `/usr/include/sys/xattr.h` (according to the man page anyway), so that should be fine. The libattr header file won't be found, but that doesn't matter, because it doesn't stop the configure check from passing.

**Comment by rrthomas** [comment] 2024-02-24 17:03
Anyway, if you can give this a try when you have a chance, I'll get another release out. It will be good to sort out macOS support!

**Comment by kapfab** [comment] 2024-02-24 18:23
Same result as it can’t find `attr/attributes.h`.

**Comment by rrthomas** [comment] 2024-02-24 19:03
Thanks for bearing with me! I believe that header isn't needed either, so I've removed the reference to it. Try again?

**Comment by rrthomas** [comment] 2024-02-24 19:05
Hmm, I take it back, it could be needed to define `ENOATTR` on some systems, so I'll restore its use but make it optional.

**Comment by rrthomas** [comment] 2024-02-24 19:06
Done!

**Comment by kapfab** [comment] 2024-02-24 23:38
`plpfuse` now gets built along with the other modules.

But I’m afraid it won’t be that simple…

There are two compile warnings that need a bit of attention:
```
fuse.c:575:19: warning: initialization of 'int (*)(const char *, const char *, const char *, size_t,  int,  uint32_t)' {aka 'int (*)(const char *, const char *, const char *, long unsigned int,  int,  unsigned int)'} from incompatible pointer type 'int (*)(const char *, const char *, const char *, size_t,  int)' {aka 'int (*)(const char *, const char *, const char *, long unsigned int,  int)'} [-Wincompatible-pointer-types]
  575 |   .setxattr     = plp_setxattr,
      |                   ^~~~~~~~~~~~
fuse.c:575:19: note: (near initialization for 'plp_oper.setxattr')
fuse.c:576:19: warning: initialization of 'int (*)(const char *, const char *, char *, size_t,  uint32_t)' {aka 'int (*)(const char *, const char *, char *, long unsigned int,  unsigned int)'} from incompatible pointer type 'int (*)(const char *, const char *, char *, size_t)' {aka 'int (*)(const char *, const char *, char *, long unsigned int)'} [-Wincompatible-pointer-types]
  576 |   .getxattr     = plp_getxattr,
      |                   ^~~~~~~~~~~~
fuse.c:576:19: note: (near initialization for 'plp_oper.getxattr')
```

For reference, an extract of `man setxattr` on macOS:
```
#include <sys/xattr.h>

int setxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int
options);

setxattr() associates name and data together as an attribute of path.

An extended attribute's name is a simple NULL-terminated UTF-8 string. Value is a pointer to a data
buffer of size bytes containing textual or binary data to be associated with the extended attribute.
Position specifies the offset within the extended attribute. In the current implementation, only the
resource fork extended attribute makes use of this argument. For all others, position is reserved and
should be set to zero.
```

whereas on Linux:
```
#include <sys/xattr.h>

int setxattr(const char *path, const char *name, const void value[.size], size_t size, u_int32_t
position, int flags);

setxattr() sets the value of the extended attribute identified by name and associated with the given path
in the filesystem. The size argument specifies the size (in bytes) of value; a zero-length value is
permitted.

An extended attribute name is a null-terminated string. The name includes a namespace prefix; there may
be several, disjoint namespaces associated with an individual inode. The value of an extended attribute
is a chunk of arbitrary textual or binary data of specified length.
```

**Comment by mikeydelamonde** [comment] 2024-02-25 11:42
Just to finish this off - I built it again and now it works - just browsed the filesystem using the MacOS Finder! That's everything working so thanks to all of you for getting it going.

**Comment by kapfab** [comment] 2024-02-25 12:05
That's good news but I'm surprised all works fine with the differences between both xattr implementations!

**Comment by rrthomas** [comment] 2024-02-25 20:47
@kapfab I'm less surprised this works. Note that plpfuse does not call `setxattr`. What matters is the API for the `setxattr` member of the `fuse_operations` struct.

Here, macFUSE cleverly reverses the last two arguments, so that, up to the penultimate, they are compatible with Linux. I guess this happens to work with the macOS ABI, in that the last argument `position` is passed but ignored? Note further from the macOS man page: "In the current implementation, only the resource fork extended attribute makes use of this argument. For all others, position is reserved and should be set to zero."

I can't find any relevant documentation for macFUSE, so I'm not sure what I can do other than replicate what happens in macFUSE's `fuse.h`:

```
#ifdef __APPLE__
	int (*setxattr) (const char *, const char *, const char *, size_t, int, uint32_t);
#else
	int (*setxattr) (const char *, const char *, const char *, size_t, int);
#endif
```

…which is not great, but hey. I'll do it.

**Comment by kapfab** [comment] 2024-02-25 20:53
Not great but that's a lesser evil!

**Comment by rrthomas** [comment] 2024-02-25 20:53
Fix pushed; I'd be most grateful if you can try again!

**Comment by kapfab** [comment] 2024-02-25 22:01
There’s a call to `plp_getxattr` in `plp_setxattr` that needs to be tweaked for macOS.
```
fuse.c:418:27: warning: ISO C does not support '[[]]' attributes before C2X [-Wpedantic]
  418 |                         , [[__maybe_unused__]] uint32_t position
      |                           ^
fuse.c:443:27: warning: ISO C does not support '[[]]' attributes before C2X [-Wpedantic]
  443 |                         , [[__maybe_unused__]] uint32_t position
      |                           ^
fuse.c: In function 'plp_setxattr':
fuse.c:459:5: error: too few arguments to function 'plp_getxattr'
  459 |     plp_getxattr(path - 1, name, oxattr, XATTR_MAXLEN);
      |     ^~~~~~~~~~~~
fuse.c:416:12: note: declared here
  416 | static int plp_getxattr(const char *path, const char *name, char *value, size_t size
      |            ^~~~~~~~~~~~
make: *** [fuse.o] Error 1
```

**Comment by kapfab** [comment] 2024-02-25 22:05
Out-of-context side note: we can remove the `intl/VERSION` paragraph from the macOS instructions in the `README` file, there’s no more conflicting file now you removed the in-tree `gettext`.

**Comment by rrthomas** [comment] 2024-02-25 22:10
> Out-of-context side note: we can remove the `intl/VERSION` paragraph from the macOS instructions in the `README` file, there’s no more conflicting file now you removed the in-tree `gettext`.

Many thanks, I wondered about that.

**Comment by rrthomas** [comment] 2024-02-25 22:12
> There’s a call to `plp_getxattr` in `plp_setxattr` that needs to be tweaked for macOS.

Fixed!

**Comment by kapfab** [comment] 2024-02-25 22:41
> > There’s a call to `plp_getxattr` in `plp_setxattr` that needs to be tweaked for macOS.
> 
> Fixed!

Builds fine now!

**Comment by kapfab** [comment] 2024-02-25 22:46
> > Out-of-context side note: we can remove the `intl/VERSION` paragraph from the macOS instructions in the `README` file, there’s no more conflicting file now you removed the in-tree `gettext`.
> 
> Many thanks, I wondered about that.

I think we can also get rid of the `-I$(top_srcdir)/intl` in modules’ `Makefile.am`.

**Comment by kapfab** [comment] 2024-02-25 23:33
> I have added a version check for libreadline to git master; I would be most obliged if someone could check that it now gives a nice error on macOS when GNU readline (or sufficiently new libedit) is not installed.

Sorry, forgot to get back to you on this: I get the warning without GNU readline and the build goes on without the readline-related features (`libedit` is still linked because of `LIBS = -lreadline` but that’s not a big deal).

**Comment by rrthomas** [comment] 2024-02-26 11:06
Thanks again, @kapfab, I have fixed both of the above (and a minor fix for a printf format bug).

Please can you confirm that the build still works? Then I'll release.

**Comment by kapfab** [comment] 2024-02-26 13:30
No problem, that’s not an easy task for you to make these changes without having a Mac at hand!

And after all, there wouldn’t be these macOS-related issues if I hadn’t added macOS support, so I’m just assuming my responsibility here…

**Comment by rrthomas** [comment] 2024-02-26 13:45
> Latest changes in `lib/plpintl.h` broke something. Build fails unless I force GNU `gettext` to be used (this worked fine without it before), and even `--disable-nls` do not prevent the error

`--disable-nls` should work again (it actually doesn't work on GNU systems; it seems that in C++ at least you can't turn off NLS). But on systems that don't have NLS built in it should be OK!

> Also, when I rollback this specific change, it builds but `libreadline` and `libhistory` are no more linked in the `plpftp` binary (I can’t find `LIBREADLINE` and `LIBHISTORY` defined in the `Makefile`).

The correct libraries should be linked via `LIBS` now I've fixed the readline detection.

**Comment by kapfab** [comment] 2024-02-26 14:00
Without GNU `readline`, it builds without the related features but `libedit` is still linked (`LIBS = -lreadline`).
With GNU `readline`, builds with `libreadline` linked but not `libhistory` (`LIBS = -lreadline`).

**Comment by kapfab** [comment] 2024-02-26 14:02
This `libhistory` issue is not actually linked to our latest changes.
It was linked in f371f8df548d03e59cb534dcf6bf73e22b4a384c (10.0.17), not in e59ab8a82fe45fe3455515312534e96c47caa116 (10.0.18).

**Comment by rrthomas** [comment] 2024-02-26 14:17
Indeed, AX_LIB_READLINE never adds `-lhistory` to `LIBS`. Nor can I see that it's needed: `libreadline` contains all the `*history*` symbols.

**Comment by rrthomas** [comment] 2024-02-26 14:21
I have fixed `LIBS` so that `-lreadline` is removed when Readline is not new enough.

**Comment by kapfab** [comment] 2024-02-26 14:24
Before this commit, `otool -L plpftp/.libs/plpftp` gives me (among others):
```
/usr/local/lib/plptools/libplp.0.dylib (compatibility version 1.0.0, current version 1.0.0)
/opt/homebrew/opt/readline/lib/libreadline.8.dylib (compatibility version 8.2.0, current version 8.2.0)
/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
/opt/homebrew/opt/readline/lib/libhistory.8.dylib (compatibility version 8.2.0, current version 8.2.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1600.157.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)
```
and after:
```
/usr/local/lib/plptools/libplp.0.dylib (compatibility version 1.0.0, current version 1.0.0)
/opt/homebrew/opt/readline/lib/libreadline.8.dylib (compatibility version 8.2.0, current version 8.2.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1600.157.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)
```
I’ll check if history works without it.

**Comment by rrthomas** [comment] 2024-02-26 14:27
Yes indeed: libhistory exists and contains symbols. I assume this is for historical reasons; I have looked at some quite old (>10 years) code I have written to add readline history to Lua, and it doesn't link with libhistory. The readline manual doesn't mention linking at all. I will look at the source distribution.

**Comment by rrthomas** [comment] 2024-02-26 14:35
Well, this is most frustrating: I can't seem to find documentation of linking Readline anywhere.

However, the Readline source distro contains some examples, and the only ones that link with libhistory are those that use only history functions. At least one example uses history functions (as well as readline functions) and links only against libreadline.

**Comment by kapfab** [comment] 2024-02-26 14:47
Well, the history feature doesn’t work even with the latest binary having `libhistory` linked…

I have a binary from a few months ago where it works:
```
/usr/local/lib/plptools/libplp.0.dylib (compatibility version 1.0.0, current version 1.0.0)
/opt/homebrew/opt/readline/lib/libreadline.8.dylib (compatibility version 8.2.0, current version 8.2.0)
/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
/opt/homebrew/opt/readline/lib/libhistory.8.dylib (compatibility version 8.2.0, current version 8.2.0)
/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1600.151.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
```

I’ll try to go back a few commits to find where it went wrong.

**Comment by rrthomas** [comment] 2024-02-26 14:53
I know what's wrong! `HAVE_LIBHISTORY` is no longer defined. I'll fix that test.

**Comment by rrthomas** [comment] 2024-02-26 15:00
Fixed. Don't be alarmed by the introduction of `./bootstrap` (yet!), as for now it doesn't do anything. Instead of running `autoreconf -fi`, run `./bootstrap --skip-po`.

**Comment by kapfab** [comment] 2024-02-26 18:23
Doesn’t seem to please macOS, and I don’t know what the actual error is…
```
bootstrap: warning: Consider installing git-merge-changelog from gnulib.
bootstrap: running: autopoint --force
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gm4: unrecognized option `--gnu'
Try `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gm4 --help' for more information.
autom4te: error: /usr/bin/gm4 failed with exit status: 1
Copying file ABOUT-NLS
Creating directory build-aux
Copying file build-aux/config.rpath
Copying file m4/codeset.m4
Copying file m4/extern-inline.m4
Copying file m4/fcntl-o.m4
Copying file m4/gettext.m4
Copying file m4/iconv.m4
Copying file m4/intdiv0.m4
Copying file m4/intl.m4
Copying file m4/intldir.m4
Copying file m4/intlmacosx.m4
Copying file m4/intmax.m4
Copying file m4/inttypes-pri.m4
Copying file m4/lcmessage.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/lock.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/printf-posix.m4
Copying file m4/progtest.m4
Copying file m4/threadlib.m4
Copying file m4/visibility.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
Copying file po/boldquot.sed
Copying file po/en@boldquot.header
Copying file po/en@quot.header
Copying file po/insert-header.sin
Copying file po/quot.sed
Copying file po/remove-potcdate.sin
bootstrap: running: /opt/homebrew/bin/glibtoolize --quiet
bootstrap: running: git clone --shallow-since=2024-02-26 'git://git.sv.gnu.org/gnulib.git' 'gnulib'
Cloning into 'gnulib'...
remote: Counting objects: 282621, done.
remote: Compressing objects: 100% (35788/35788), done.
remote: Total 282621 (delta 249977), reused 278887 (delta 246735)
Receiving objects: 100% (282621/282621), 71.03 MiB | 798.00 KiB/s, done.
Resolving deltas: 100% (249977/249977), done.
Checking connectivity: 282618, done.
bootstrap: running: git submodule init -- gnulib
Submodule 'gnulib' (git://git.sv.gnu.org/gnulib.git) registered for path 'gnulib'
bootstrap: running: git submodule update -- gnulib
bootstrap: running: git submodule init -- gl-mod/bootstrap
Submodule 'gl-mod/bootstrap' (https://github.com/gnulib-modules/bootstrap.git) registered for path 'gl-mod/bootstrap'
bootstrap: running: git submodule update -- gl-mod/bootstrap
Cloning into 'gl-mod/bootstrap'...
Submodule path 'gl-mod/bootstrap': checked out '6866c3d5d81a1456a1885d601e6ad0da180f6bd4'
bootstrap: running: gnulib/gnulib-tool --no-libtool --no-changelog --aux-dir=build-aux --m4-base=m4 --local-dir=gl --local-dir=gl-mod/bootstrap --source-base=libgnu --symlink --import bootstrap
gnulib/gnulib-tool: 'join' program is buggy. Consider installing GNU coreutils.
```

**Comment by rrthomas** [comment] 2024-02-26 19:06
First, apologies for what might look like unnecessary changes and additions to the build system. There is method here: I'm bringing plptools in line with other legacy projects that I maintain by using gnulib and bootstrap.

As to your particular problem: this was new to me (I maintain various projects which all use gnulib and bootstrap, and this is the first time I've seen this error). It is in fact new, as gnulib's ChangeLog shows that this check was introduced only last month.

It turns out that macOS's `join` is broken (i.e. not POSIX-compliant.) The workaround is to do what is suggested and install coreutils.

**Comment by kapfab** [comment] 2024-02-26 21:31
I already had `coreutils` installed but `brew` prefixes them with a `'g'` to avoid shadowing the native macOS commands.
And in addition to `join`, the bootstrap also complained about `m4` (`unrecognized option '--gnu'`) so I had to install a recent `m4` version (yes, macOS comes with GNU M4 version 1.4.6 from 2006… don’t ask me why!).

All these commands have aliases with their default names in dedicated directories that can added to the PATH before `/usr/bin` to take over the native ones.

So that means one has to run the following commands to make the build succeed on macOS:
```
PATH="$(brew --prefix coreutils)/libexec/gnubin:$(brew --prefix m4)/bin:$PATH" ./bootstrap --skip-po
LDFLAGS="-L$(brew --prefix readline)/lib" CPPFLAGS="-I$(brew --prefix readline)/include" ./configure
make
```

I’m not familiar with `gnulib`, it doesn’t seem to me to be necessary (for `plptools` on macOS, I mean), but I’d say it can’t hurt.

But unless I misunderstand where `gnulib bootstrap` is trying to go, it sort of misses its target with macOS from a user perspective since using it seems to bring more contraints and specificities than not using it.

**Comment by rrthomas** [comment] 2024-02-26 22:23
> And in addition to `join`, the bootstrap also complained about `m4` (`unrecognized option '--gnu'`) so I had to install a recent `m4` version

Yup, I'm familiar with that.

> (yes, macOS comes with GNU M4 version 1.4.6 from 2006… don’t ask me why!).

Because fairly soon after Mac OS X's release (as it was then), Apple stopped updating GPL'ed utilities, and/or removed them from Mac OS, so they could patch upstream code without sharing their patches.

> So that means one has to run the following commands to make the build succeed on macOS:
> 
> ```
> PATH="$(brew --prefix coreutils)/libexec/gnubin:$(brew --prefix m4)/bin:$PATH" ./bootstrap --skip-po
> LDFLAGS="-L$(brew --prefix readline)/lib" CPPFLAGS="-I$(brew --prefix readline)/include" ./configure
> make
> ```

Yup. I think I'll have to set up GitHub CI for plptools; that will then provide a recipe for macOS users that will be tested for each commit. I have found this approach works well with other projects.

> I’m not familiar with `gnulib`, it doesn’t seem to me to be necessary (for `plptools` on macOS, I mean), but I’d say it can’t hurt.

The idea with gnulib is that I stop worrying about portability, just program to POSIX (plus in some cases GNU APIs), and gnulib polyfills them for me where they're lacking/buggy (including on GNU systems!). I'd avoided doing this with plptools in the past because it only worked on UNIX, and for most of the time I've maintained it, that has meant GNU/Linux; but now that it's clearly workable on macOS (and who knows in future, maybe Windows), I might as well make portability someone else's problem (namely, the authors of gnulib).

> But unless I misunderstand where `gnulib bootstrap` is trying to go, it sort of misses its target with macOS from a user perspective since using it seems to bring more contraints and specificities than not using it.

Gnulib requires GNU tools in a very few cases (actually, m4 is the only one that I can think of), but mostly just requires POSIX compatibility; not an unreasonable ask, in my view.

> EDIT: the `plpftp` binary still doesn’t have `libhistory` linked and doesn’t have the history feature working

You might check whether readline is built differently in brew, but I doubt it (you can check that `nm LIBREADLINE-FILE.dylib | grep history` returns some results). Does libedit offer the readline history APIs? I can't find any evidence that it does. To get history and line editing, you'll need to make sure that readline is installed, so that AX_LIB_READLINE finds libreadline before libedit. libhistory simply isn't relevant here, as far as I can tell.

**Comment by rrthomas** [comment] 2024-02-26 22:26
@kapfab I can save some of your time by getting macOS CI up and running before asking you to try a build again yourself: that will let me see that the code at least builds smoothly (and have a recipe that does it).

**Comment by kapfab** [comment] 2024-02-26 22:55
> I might as well make portability someone else's problem (namely, the authors of gnulib).

That’s a very good point.

> > EDIT: the `plpftp` binary still doesn’t have `libhistory` linked and doesn’t have the history feature working
> 
> You might check whether readline is built differently in brew, but I doubt it (you can check that `nm LIBREADLINE-FILE.dylib | grep history` returns some results). Does libedit offer the readline history APIs? I can't find any evidence that it does. To get history and line editing, you'll need to make sure that readline is installed, so that AX_LIB_READLINE finds libreadline before libedit. libhistory simply isn't relevant here, as far as I can tell.

`libreadline.8.dylib` does contain the same history-related symbols as `libhistory.8.dylib` (even a few more…) and the binary does reference the expected GNU libreadline, not libedit (which is only linked when not adding the necessary `LDFLAGS` and `CPPFLAGS` for `configure`).

Still, history does not work anymore (but it works when using the same build steps with the commit before [Use AX_LIB_READLINE and check version](https://github.com/rrthomas/plptools/commit/9ca4c5494d788a65697cc0bf8c1cc5b7778f0407)).

**Comment by rrthomas** [comment] 2024-02-26 23:00
OK, I've now gotten CI working. `build-aux/build.sh` plus `.github/workflows/c-cpp.yml` now give a working idea of how to get plptools built on GNU/Linux and macOS.

Thanks very much for your investigation. I realised I had been overhasty in my changes to `ftp.cc` and had left occurrences of a symbol `HAVE_LIBHISTORY` that is no longer ever defined. Now fixed.

**Comment by kapfab** [comment] 2024-02-26 23:10
And that’s working fine now, thanks!

**Comment by rrthomas** [comment] 2024-02-26 23:15
Fantastic, you've been a trooper! Hopefully that'll keep the code building and running for another 10 years at least! I'll release 1.0.19 now. Any more problems (I'd be surprised if this whirlwind of untested development *hadn't* introduced more bugs) do file away!

At least the only code left that has lots of system-specific stuff is now hardware flow control, which seems to be one of those corners POSIX never got around to papering over.

**Comment by kapfab** [comment] 2024-02-27 00:10
You’re welcome!

We also need to update the `README` to reflect the changes for macOS:
```
macOS-specific instructions
---------------------------
       
To build plptools on macOS, you need to install the GNU Readline library,
the GNU Core Utilities and a recent version of GNU M4.

Assuming Homebrew is your package manager:

brew install readline
brew install coreutils m4

If building from a git checkout, first run:

PATH="$(brew --prefix coreutils)/libexec/gnubin:$(brew --prefix m4)/bin:$PATH" \
./bootstrap --skip-po

In order to enable readline and history support, you need to properly
configure the build:

LDFLAGS="-L$(brew --prefix readline)/lib" \
CPPFLAGS="-I$(brew --prefix readline)/include" ./configure

Then you can build and install the package:

make
make install
```

**Comment by rrthomas** [comment] 2024-02-27 06:53
I have made another release, and stripped out the macOS-specific instructions, instead referring the reader to the GitHub CI configuration. (I don't want to give the impression that I support macOS specifically—I think what should really happen here is that someone should package plptools for brew; just as I don't support Fedora, Debian, Ubuntu etc., but rely on packagers.)

**Comment by kapfab** [comment] 2024-02-27 07:32
That's fine. I will make the brew formula, everything seems to be working and stable now (install glitch fixed and plpfuse confirmed to work).
